### ISSUE TITLE
Contribution as in DWoC

### ISSUE THREAD

**Issue by Aniket-508** [websycode/Lets-Shop#1]
Hey, I wanted to contribute to this repo but when I looked up, there were no code or issues. Any thoughts of how should I start drafting my proposal in order to contribute in coming DWoC?

**Comment by aakankshabhende** [comment]
You can start contributing to this project once DWoC officially starts by creating new issues @Aniket-508

**Comment by aakankshabhende** [comment]
We will be making this project from scratch so you can create suitable and valid issues according to you
