### ISSUE TITLE
Create a responsive Home Page for this website.

### ISSUE THREAD

**Issue by aakankshabhende** [websycode/Lets-Shop#3]

**Comment by siddhantprateek** [comment]
I want to contribute to this project, but I don't see any UI design to refer to.  Should open an issue to create a UI design for this project.

**Comment by aakankshabhende** [comment]
You can create a rough UI and share screenshots here @siddhantprateek . If accepted you can start its implementation.

**Comment by harshit995** [comment]
pls assign it to me i will create it

**Comment by harshit995** [comment]
pls reply @aakankshabhende

**Comment by aakankshabhende** [comment]
You can start working on it @harshit995 .I'll assign this issue after coding period officially begins.
